[2022-11-21 21:43:11,014] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: bash_operator.download_launches scheduled__2022-11-21T01:58:00+00:00 [queued]>
[2022-11-21 21:43:11,031] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: bash_operator.download_launches scheduled__2022-11-21T01:58:00+00:00 [queued]>
[2022-11-21 21:43:11,032] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-11-21 21:43:11,032] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-11-21 21:43:11,033] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-21 21:43:11,044] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): download_launches> on 2022-11-21 01:58:00+00:00
[2022-11-21 21:43:11,051] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'bash_operator', 'download_launches', 'scheduled__2022-11-21T01:58:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/bash_example.py', '--cfg-path', '/tmp/tmpoj8pynpb', '--error-file', '/tmp/tmpon7rgqgg']
[2022-11-21 21:43:11,053] {standard_task_runner.py:77} INFO - Job 6: Subtask download_launches
[2022-11-21 21:43:11,048] {standard_task_runner.py:52} INFO - Started process 341 to run task
[2022-11-21 21:43:11,100] {logging_mixin.py:109} INFO - Running <TaskInstance: bash_operator.download_launches scheduled__2022-11-21T01:58:00+00:00 [running]> on host e6f0f1db9976
[2022-11-21 21:43:11,149] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bash_operator
AIRFLOW_CTX_TASK_ID=download_launches
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T01:58:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T01:58:00+00:00
[2022-11-21 21:43:11,151] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-21 21:43:11,153] {subprocess.py:74} INFO - Running command: ['bash', '-c', "curl -o /datalake/bronze/ -L 'https://ll.thespacedevs.com/2.0.0/launch/upcoming'"]
[2022-11-21 21:43:11,167] {subprocess.py:85} INFO - Output:
[2022-11-21 21:43:11,178] {subprocess.py:89} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-21 21:43:11,179] {subprocess.py:89} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-21 21:43:16,172] {subprocess.py:89} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
[2022-11-21 21:43:29,807] {subprocess.py:89} INFO -   0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:17 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:18 --:--:--     0Warning: Failed to create the file /datalake/bronze/: No such file or
[2022-11-21 21:43:29,818] {subprocess.py:89} INFO - Warning: directory
[2022-11-21 21:43:29,819] {subprocess.py:89} INFO -   4 25360    4  1016    0     0     54      0  0:07:49  0:00:18  0:07:31   219
[2022-11-21 21:43:29,820] {subprocess.py:89} INFO - curl: (23) Failed writing body (0 != 1016)
[2022-11-21 21:43:29,821] {subprocess.py:93} INFO - Command exited with return code 23
[2022-11-21 21:43:29,825] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2022-11-21 21:43:29,842] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=bash_operator, task_id=download_launches, execution_date=20221121T015800, start_date=20221121T214311, end_date=20221121T214329
[2022-11-21 21:43:29,856] {standard_task_runner.py:91} ERROR - Failed to execute job 6 for task download_launches
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2022-11-21 21:43:29,901] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-11-21 21:43:29,932] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-21 21:45:04,220] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: bash_operator.download_launches manual__2022-11-21T21:45:02.928692+00:00 [queued]>
[2022-11-21 21:45:04,241] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: bash_operator.download_launches manual__2022-11-21T21:45:02.928692+00:00 [queued]>
[2022-11-21 21:45:04,243] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-11-21 21:45:04,244] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-11-21 21:45:04,244] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-21 21:45:04,259] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): download_launches> on 2022-11-21 21:45:02.928692+00:00
[2022-11-21 21:45:04,268] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'bash_operator', 'download_launches', 'manual__2022-11-21T21:45:02.928692+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/bash_example.py', '--cfg-path', '/tmp/tmplslm1z1y', '--error-file', '/tmp/tmp8vjqvs1_']
[2022-11-21 21:45:04,269] {standard_task_runner.py:77} INFO - Job 7: Subtask download_launches
[2022-11-21 21:45:04,265] {standard_task_runner.py:52} INFO - Started process 425 to run task
[2022-11-21 21:45:04,317] {logging_mixin.py:109} INFO - Running <TaskInstance: bash_operator.download_launches manual__2022-11-21T21:45:02.928692+00:00 [running]> on host e6f0f1db9976
[2022-11-21 21:45:04,370] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bash_operator
AIRFLOW_CTX_TASK_ID=download_launches
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T21:45:02.928692+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-21T21:45:02.928692+00:00
[2022-11-21 21:45:04,372] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-21 21:45:04,373] {subprocess.py:74} INFO - Running command: ['bash', '-c', "curl -o /datalake/bronze/launches.json -L 'https://ll.thespacedevs.com/2.0.0/launch/upcoming'"]
[2022-11-21 21:45:04,385] {subprocess.py:85} INFO - Output:
[2022-11-21 21:45:04,399] {subprocess.py:89} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-21 21:45:04,400] {subprocess.py:89} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-21 21:45:05,125] {subprocess.py:89} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2022-11-21 21:45:05,550] {subprocess.py:89} INFO - Warning: Failed to create the file /datalake/bronze/launches.json: No such
[2022-11-21 21:45:05,551] {subprocess.py:89} INFO - Warning: file or directory
[2022-11-21 21:45:05,552] {subprocess.py:89} INFO -   4 25360    4  1037    0     0    900      0  0:00:28  0:00:01  0:00:27   900
[2022-11-21 21:45:05,553] {subprocess.py:89} INFO - curl: (23) Failed writing body (0 != 1037)
[2022-11-21 21:45:05,554] {subprocess.py:93} INFO - Command exited with return code 23
[2022-11-21 21:45:05,560] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2022-11-21 21:45:05,586] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=bash_operator, task_id=download_launches, execution_date=20221121T214502, start_date=20221121T214504, end_date=20221121T214505
[2022-11-21 21:45:05,602] {standard_task_runner.py:91} ERROR - Failed to execute job 7 for task download_launches
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2022-11-21 21:45:05,618] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-11-21 21:45:05,666] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-21 23:33:23,115] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: bash_operator.download_launches manual__2022-11-21T23:33:20.556781+00:00 [queued]>
[2022-11-21 23:33:23,141] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: bash_operator.download_launches manual__2022-11-21T23:33:20.556781+00:00 [queued]>
[2022-11-21 23:33:23,143] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-11-21 23:33:23,143] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-11-21 23:33:23,145] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-21 23:33:23,162] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): download_launches> on 2022-11-21 23:33:20.556781+00:00
[2022-11-21 23:33:23,174] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'bash_operator', 'download_launches', 'manual__2022-11-21T23:33:20.556781+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/bash_example.py', '--cfg-path', '/tmp/tmpyo4qybcu', '--error-file', '/tmp/tmpq4lfiuhv']
[2022-11-21 23:33:23,176] {standard_task_runner.py:77} INFO - Job 62: Subtask download_launches
[2022-11-21 23:33:23,170] {standard_task_runner.py:52} INFO - Started process 4690 to run task
[2022-11-21 23:33:23,278] {logging_mixin.py:109} INFO - Running <TaskInstance: bash_operator.download_launches manual__2022-11-21T23:33:20.556781+00:00 [running]> on host e6f0f1db9976
[2022-11-21 23:33:23,350] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bash_operator
AIRFLOW_CTX_TASK_ID=download_launches
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T23:33:20.556781+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-21T23:33:20.556781+00:00
[2022-11-21 23:33:23,352] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-21 23:33:23,355] {subprocess.py:74} INFO - Running command: ['bash', '-c', "curl -o /opt/***/datalake/bronze/launches.json -L 'https://ll.thespacedevs.com/2.0.0/launch/upcoming'"]
[2022-11-21 23:33:23,369] {subprocess.py:85} INFO - Output:
[2022-11-21 23:33:23,382] {subprocess.py:89} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-21 23:33:23,383] {subprocess.py:89} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-21 23:33:23,983] {subprocess.py:89} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2022-11-21 23:33:24,953] {subprocess.py:89} INFO -   3 26668    3  1015    0     0    693      0  0:00:38  0:00:01  0:00:37   693100 26668  100 26668    0     0  16985      0  0:00:01  0:00:01 --:--:--  234k
[2022-11-21 23:33:24,955] {subprocess.py:93} INFO - Command exited with return code 0
[2022-11-21 23:33:24,998] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=bash_operator, task_id=download_launches, execution_date=20221121T233320, start_date=20221121T233323, end_date=20221121T233324
[2022-11-21 23:33:25,054] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-21 23:33:25,122] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
